import type { ISolarflowState } from "../../models/ISolarflowState";

export const hyperControlStates: ISolarflowState[] = [
  {
    nameDe: "Einzustellende Ausgangsleistung",
    nameEn: "Control of the output limit",
    type: "number",
    def: 0,
    title: "setOutputLimit",
    role: "value.power",
    read: true,
    write: true,
    min: 0,
    max: 1200,
    unit: "W",
  },
  {
    nameDe: "Einzustellende Eingangsleistung",
    nameEn: "Control of the input limit",
    type: "number",
    def: 0,
    title: "setInputLimit",
    role: "value.power",
    read: true,
    write: true,
    min: 0,
    max: 1200,
    step: 1,
    unit: "W",
  },
  {
    nameDe: "AC Schalter",
    nameEn: "AC switch",
    type: "boolean",
    def: false,
    title: "acSwitch",
    role: "switch",
    read: true,
    write: true,
  },
  {
    nameDe: "AC Modus",
    nameEn: "AC mode",
    type: "number",
    def: 0,
    title: "acMode",
    role: "switch",
    min: 0,
    max: 2,
    step: 1,
    read: true,
    write: true,
    states: {
      0: "Nothing",
      1: "AC input mode",
      2: "AC output mode",
    },
  },
  {
    nameDe: "Überschüssige Energie exportieren",
    nameEn: "Grid reverse (export excess energy)",
    type: "number",
    def: 0,
    title: "gridReverse",
    role: "value",
    read: true,
    write: true,
    min: 0,
    max: 2,
    step: 1,
    states: {
      0: "disabled",
      1: "allow",
      2: "forbidden",
    },
  },
  {
    nameDe: "Geräte Automation Limit (negativ = Laden, positiv = Einspeisen)",
    nameEn: "Device Automation Limit (negative = charging, positive = feed in)",
    type: "number",
    def: 0,
    title: "setDeviceAutomationInOutLimit",
    role: "value.power",
    read: true,
    write: true,
    min: -1200,
    max: 1200,
    unit: "W",
  },
  {
    nameDe: "Maximal akzeptable Ausgangsleistung",
    nameEn: "highest acceptable output power",
    type: "number",
    def: 0,
    title: "inverseMaxPower",
    role: "value.power",
    read: true,
    write: true,
    min: 0,
    max: 1200,
    unit: "W",
  },
];
