import type { ISolarflowState } from "../../models/ISolarflowState";

// Control states that are identical across all device models
export const sharedControlStates: ISolarflowState[] = [
  {
    nameDe: "Energieplan-Einstellung",
    nameEn: "Energyplan",
    type: "number",
    def: 0,
    title: "autoModel",
    role: "value",
    read: true,
    write: true,
    states: {
      0: "Nothing",
      6: "Battery priority mode",
      7: "Appointment mode",
      8: "Smart Matching Mode",
      9: "Smart CT Mode",
      10: "Electricity Price",
    },
  },
  {
    nameDe: "Setzen des Lade-Limits",
    nameEn: "Control of the charge limit",
    title: "chargeLimit",
    type: "number",
    def: 0,
    role: "value.battery",
    read: true,
    write: true,
    min: 40,
    max: 100,
    unit: "%",
  },
  {
    nameDe: "Setzen des Entlade-Limits",
    nameEn: "Control of the discharge limit",
    type: "number",
    def: 0,
    title: "dischargeLimit",
    role: "value.battery",
    read: true,
    write: true,
    min: 0,
    max: 50,
    unit: "%",
  },
  {
    nameDe: "Verhalten wenn minimale reservierte Ladung erreicht",
    nameEn: "Behavior when minimum reserved charge is reached",
    type: "number",
    def: 0,
    title: "hubState",
    role: "value",
    read: true,
    write: true,
    min: 0,
    max: 1,
    states: {
      0: "Stop output and standby",
      1: "Stop output and shut down",
    },
  },
  {
    nameDe: "Niedrige Batteriespannung erkannt",
    nameEn: "Low Voltage on battery detected",
    type: "boolean",
    def: false,
    title: "lowVoltageBlock",
    role: "indicator.lowbat",
    read: true,
    write: false,
  },
  {
    nameDe: "Auf 100% laden, Akku muss kalibriert werden!",
    nameEn: "Charge to 100%, battery needs to be calibrated",
    type: "boolean",
    def: false,
    title: "fullChargeNeeded",
    role: "indicator.lowbat",
    read: true,
    write: false,
  },
];
