/* eslint-disable @typescript-eslint/indent */
import { ISolarflowState } from "../models/ISolarflowState";
import { sharedStates } from "./sharedStates";

export const solarflow800ProStates: ISolarflowState[] = sharedStates.concat([
  {
    title: "hyperTmp",
    nameDe: "Temperatur des Solarflow 800",
    nameEn: "Temperature of Solarflow 800",
    type: "number",
    role: "value.temperature",
    unit: "°C",
  },
  {
    title: "inverseMaxPower",
    nameDe: "Maximal akzeptabler Eingang des PV-Mikrowechselrichters",
    nameEn: "highest acceptable input power",
    type: "number",
    role: "value.power",
    unit: "W",
  },
  {
    title: "pass",
    nameDe: "Bypass an/aus",
    nameEn: "Bypass on/off",
    type: "boolean",
    role: "value",
  },
  {
    title: "autoRecover",
    nameDe: "Am nächsten Tag Bypass auf Automatik",
    nameEn: "Automatic recovery of bypass",
    type: "boolean",
    role: "value",
  },
  {
    title: "passMode",
    nameDe: "Einstellung des Bypass Modus",
    nameEn: "Setting of bypass mode",
    type: "string",
    role: "value",
  },
  {
    title: "pvBrand",
    nameDe: "Wechselrichter Hersteller",
    nameEn: "brand of inverter",
    type: "string",
    role: "value",
  },
  {
    title: "outputHomePower",
    nameDe: "Ausgangsleistung",
    nameEn: "output power",
    type: "number",
    role: "value.power",
    unit: "W",
  },
  {
    title: "outputLimit",
    nameDe: "Limit der Ausgangsleistung",
    nameEn: "limit of output power",
    type: "number",
    role: "value.power",
    unit: "W",
  },
  {
    title: "pvPower3",
    nameDe: "Leistung PV 3",
    nameEn: "solar power channel 3",
    type: "number",
    role: "value.power",
    unit: "W",
  },
  {
    title: "pvPower4",
    nameDe: "Leistung PV 4",
    nameEn: "solar power channel 4",
    type: "number",
    role: "value.power",
    unit: "W",
  },
  {
    title: "acMode",
    nameDe: "AC Modus",
    nameEn: "AC mode",
    type: "number",
    role: "value",
    states: {
      0: "Nothing",
      1: "AC input mode",
      2: "AC output mode",
    },
  },
  {
    title: "smartMode",
    nameDe: "Smart Mode",
    nameEn: "Smart Mode",
    type: "boolean",
    role: "value",
  },
]);
